### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by danieltayal07** [lxmn-22/Leetcode-Questions#4]
I would suggest a contributing.md so that it becomes clear for everyone trying to contribute here that how they can contribute in the project, i can make that if needed

**Comment by lxmn-22** [comment]
Yes, go ahead. 
Create a PR, I'll merge accordingly.

**Comment by danieltayal07** [comment]
if possible add hacktoberfest tag in the repository cause hacktoberfest web says that the repository is not participating

**Comment by lxmn-22** [comment]
OK. Done.
