### ISSUE TITLE
Add Summary in README

### ISSUE THREAD

**Issue by Zemerik** [lxmn-22/Leetcode-Questions#55]
Hey, 

To make it easier for users to locate what they are trying to find, lets a short summary section in your README which gives a brief overview of what directory contains. 

Regards, 
Zemerik

**Comment by lxmn-22** [comment]
Bro, If possible you make it for us, raise **PR**. 
I'll review it and **merge** it accordingly.

> Thank you

**Comment by Zemerik** [comment]
Sure, assign it to me and give me a few days.

**Comment by lxmn-22** [comment]
Done!

**Comment by lxmn-22** [comment]
@Zemerik, What's the update brother?

**Comment by Zemerik** [comment]
Almost Finished. Should open PR in approximately `24` hours

**Comment by lxmn-22** [comment]
Great.
